// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzaovkkbrrcajzanxowe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6YW92a2ticnJjYWp6YW54b3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzI2MjcsImV4cCI6MjA1OTI0ODYyN30.xhcxYfGn3vEnrKk-Vb4B3zHn13K5ncr7sKvfbZ2OKCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);